"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023 Ant Group Co., Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import secretflow_spec.v1.component_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Descriptions(google.protobuf.message.Message):
    """Displays multiple read-only fields in groups."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Item(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        DESC_FIELD_NUMBER: builtins.int
        TYPE_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        name: builtins.str
        """Name of the field."""
        desc: builtins.str
        type: builtins.str
        """Must be one of bool/int/float/str"""
        @property
        def value(self) -> secretflow_spec.v1.component_pb2.Attribute: ...
        def __init__(
            self,
            *,
            name: builtins.str = ...,
            desc: builtins.str = ...,
            type: builtins.str = ...,
            value: secretflow_spec.v1.component_pb2.Attribute | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["desc", b"desc", "name", b"name", "type", b"type", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    ITEMS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of the Descriptions."""
    desc: builtins.str
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Descriptions.Item]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        desc: builtins.str = ...,
        items: collections.abc.Iterable[global___Descriptions.Item] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["desc", b"desc", "items", b"items", "name", b"name"]) -> None: ...

global___Descriptions = Descriptions

@typing.final
class Table(google.protobuf.message.Message):
    """Displays rows of data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class HeaderItem(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        DESC_FIELD_NUMBER: builtins.int
        TYPE_FIELD_NUMBER: builtins.int
        name: builtins.str
        desc: builtins.str
        type: builtins.str
        """Must be one of bool/int/float/str"""
        def __init__(
            self,
            *,
            name: builtins.str = ...,
            desc: builtins.str = ...,
            type: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["desc", b"desc", "name", b"name", "type", b"type"]) -> None: ...

    @typing.final
    class Row(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        DESC_FIELD_NUMBER: builtins.int
        ITEMS_FIELD_NUMBER: builtins.int
        name: builtins.str
        desc: builtins.str
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[secretflow_spec.v1.component_pb2.Attribute]: ...
        def __init__(
            self,
            *,
            name: builtins.str = ...,
            desc: builtins.str = ...,
            items: collections.abc.Iterable[secretflow_spec.v1.component_pb2.Attribute] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["desc", b"desc", "items", b"items", "name", b"name"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    HEADERS_FIELD_NUMBER: builtins.int
    ROWS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of the Table."""
    desc: builtins.str
    @property
    def headers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Table.HeaderItem]: ...
    @property
    def rows(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Table.Row]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        desc: builtins.str = ...,
        headers: collections.abc.Iterable[global___Table.HeaderItem] | None = ...,
        rows: collections.abc.Iterable[global___Table.Row] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["desc", b"desc", "headers", b"headers", "name", b"name", "rows", b"rows"]) -> None: ...

global___Table = Table

@typing.final
class Div(google.protobuf.message.Message):
    """A division or a section of a page."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Child(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TYPE_FIELD_NUMBER: builtins.int
        DESCRIPTIONS_FIELD_NUMBER: builtins.int
        TABLE_FIELD_NUMBER: builtins.int
        DIV_FIELD_NUMBER: builtins.int
        type: builtins.str
        """Supported: descriptions, table, div."""
        @property
        def descriptions(self) -> global___Descriptions: ...
        @property
        def table(self) -> global___Table: ...
        @property
        def div(self) -> global___Div: ...
        def __init__(
            self,
            *,
            type: builtins.str = ...,
            descriptions: global___Descriptions | None = ...,
            table: global___Table | None = ...,
            div: global___Div | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["descriptions", b"descriptions", "div", b"div", "table", b"table"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["descriptions", b"descriptions", "div", b"div", "table", b"table", "type", b"type"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of the Div."""
    desc: builtins.str
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Div.Child]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        desc: builtins.str = ...,
        children: collections.abc.Iterable[global___Div.Child] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "desc", b"desc", "name", b"name"]) -> None: ...

global___Div = Div

@typing.final
class Tab(google.protobuf.message.Message):
    """A page of a report."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    DIVS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of the Tab."""
    desc: builtins.str
    @property
    def divs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Div]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        desc: builtins.str = ...,
        divs: collections.abc.Iterable[global___Div] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["desc", b"desc", "divs", b"divs", "name", b"name"]) -> None: ...

global___Tab = Tab

@typing.final
class Report(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    TABS_FIELD_NUMBER: builtins.int
    ERR_CODE_FIELD_NUMBER: builtins.int
    ERR_DETAIL_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of the Report."""
    desc: builtins.str
    err_code: builtins.int
    err_detail: builtins.str
    """Structed error detail (JSON encoded message)."""
    @property
    def tabs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Tab]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        desc: builtins.str = ...,
        tabs: collections.abc.Iterable[global___Tab] | None = ...,
        err_code: builtins.int = ...,
        err_detail: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["desc", b"desc", "err_code", b"err_code", "err_detail", b"err_detail", "name", b"name", "tabs", b"tabs"]) -> None: ...

global___Report = Report
