name: "Publish PyPI Package"
on:
  workflow_dispatch:

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: spec-deploy
        id: spec-deploy
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          GHA_Meta: "publish_pypi"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
